In [1]:
import pandas as pd
import seaborn as sn
import numpy as np
import matplotlib

In [2]:
real_day_generation = pd.read_excel('./data/0590a032-8c8e-4fc7-8c36-2982be2ea28e.xlsx')
real_day_generation

          Fecha y Hora  Tipo Tecnología  Generación Real (MWh)
0  2026-03-04 00:00:00  Termoeléctricas            4787.936052
1  2026-03-04 01:00:00  Termoeléctricas            4730.185289
2  2026-03-04 02:00:00  Termoeléctricas            4495.364462
3  2026-03-04 03:00:00  Termoeléctricas            4626.840323
4  2026-03-04 04:00:00  Termoeléctricas            4716.960340
5  2026-03-04 05:00:00  Termoeléctricas            4882.869143
6  2026-03-04 06:00:00  Termoeléctricas            4939.538586
7  2026-03-04 07:00:00  Termoeléctricas            4853.496193
8  2026-03-04 08:00:00  Termoeléctricas            4023.101372
9  2026-03-04 09:00:00  Termoeléctricas            2326.809973
10 2026-03-04 10:00:00  Termoeléctricas            1541.656940
11 2026-03-04 11:00:00  Termoeléctricas            1352.444012
12 2026-03-04 12:00:00  Termoeléctricas            1307.342813
13 2026-03-04 13:00:00  Termoeléctricas            1300.697467
14 2026-03-04 14:00:00  Termoeléctricas            1362.021192
15 2026-03-04 15:00:00  Termoeléctricas            1529.924837
16 2026-03-04 16:00:00  Termoeléctricas            1788.149635
17 2026-03-04 17:00:00  Termoeléctricas            2227.655506
18 2026-03-04 18:00:00  Termoeléctricas            3053.856667
19 2026-03-04 19:00:00  Termoeléctricas            4448.826598
20 2026-03-04 20:00:00  Termoeléctricas            5426.791088
21 2026-03-04 21:00:00  Termoeléctricas            5040.645241
22 2026-03-04 22:00:00  Termoeléctricas            5061.137521
23 2026-03-04 23:00:00  Termoeléctricas            5053.084294

In [3]:
energy_program_df = pd.read_excel('./data/PRG260304.xlsx')
energy_program_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,NaN,NaN,Periodo Desde:,NaN,2026-03-04 00:00:00,2026-03-08 00:00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,COORDINADOR ELÉCTRICO NACIONAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2026-03-04 00:00:00,TP23(E20:AC613),1,2,3.000000,4.000000,5.00000,6,...,16.000000,17.000000,18.000000,19.000000,20.000000,21.000000,22.000000,23.000000,24.000000,NaN
3,NaN,NaN,Costos Operación,NaN,208.868476,207.960316,211.076290,207.966849,209.63161,211.176561,...,43.021759,43.021759,77.715207,79.988173,188.745792,216.143117,213.750766,214.749757,209.849995,3355.263189
4,NaN,NaN,Costos Encendido/Detención,NaN,13.60937,0,0.002821,0.000000,0.00000,0,...,0.000000,0.000000,94.600028,0.143171,2.156200,50.468145,0.000000,0.000000,0.000000,189.350819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983,NaN,NaN,Exportación Referencial SEN-SADI N+1,NaN,1,2,3.000000,4.000000,5.00000,6,...,16.000000,17.000000,18.000000,19.000000,20.000000,21.000000,22.000000,23.000000,24.000000,Total
1984,NaN,NaN,Total,Total,0,0,0.000000,0.000000,0.00000,0,...,80.000000,80.000000,80.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,640
1985,NaN,NaN,PFV-ANDES2A,ANDES_2A_FV,0,0,0.000000,0.000000,0.00000,0,...,80.000000,80.000000,80.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,640

In [4]:
thermal_row = energy_program_df[energy_program_df['Unnamed: 2'] == "Térmicas"].index[0]
data_row = energy_program_df.iloc[thermal_row + 1, :] # The "Total" is usually one row below the category header

print(data_row)

Unnamed: 0         NaN
Unnamed: 1         NaN
Unnamed: 2       Total
Unnamed: 3       Total
Unnamed: 4      4942.6
Unnamed: 5      4922.4
Unnamed: 6      4973.8
Unnamed: 7      4939.7
Unnamed: 8      4967.8
Unnamed: 9      4967.7
Unnamed: 10     4782.6
Unnamed: 11     4786.3
Unnamed: 12     3517.7
Unnamed: 13     1279.8
Unnamed: 14     1254.2
Unnamed: 15     1254.2
Unnamed: 16     1254.2
Unnamed: 17     1254.2
Unnamed: 18     1254.2
Unnamed: 19     1254.2
Unnamed: 20     1254.2
Unnamed: 21     2026.1
Unnamed: 22     2116.0
Unnamed: 23     4434.8
Unnamed: 24     5086.9
Unnamed: 25     5023.1
Unnamed: 26     5058.3
Unnamed: 27     5052.6
Unnamed: 28    81657.6
Name: 977, dtype: object

In [5]:
# Need to get 'Unnamed: 4' to 'Unnamed: 27'
programmed_day_generation = data_row.iloc[4:28]
programmed_day_generation

Unnamed: 4     4942.6
Unnamed: 5     4922.4
Unnamed: 6     4973.8
Unnamed: 7     4939.7
Unnamed: 8     4967.8
Unnamed: 9     4967.7
Unnamed: 10    4782.6
Unnamed: 11    4786.3
Unnamed: 12    3517.7
Unnamed: 13    1279.8
Unnamed: 14    1254.2
Unnamed: 15    1254.2
Unnamed: 16    1254.2
Unnamed: 17    1254.2
Unnamed: 18    1254.2
Unnamed: 19    1254.2
Unnamed: 20    1254.2
Unnamed: 21    2026.1
Unnamed: 22    2116.0
Unnamed: 23    4434.8
Unnamed: 24    5086.9
Unnamed: 25    5023.1
Unnamed: 26    5058.3
Unnamed: 27    5052.6
Name: 977, dtype: object

In [9]:
total_excess = np.sum(real_day_generation['Generación Real (MWh)'][0:24]) - np.sum(programmed_day_generation[0:24])
total_excess

3219.7355436583894

In [ ]:
## we define the morning to be from 6 am to 11 am
morning_excess = np.sum(real_day_generation['Generación Real (MWh)'][6:11]) - np.sum(programmed_day_generation[6:11])
morning_excess

2064.003063811997

In [ ]:
#we define the afternoon excess to be from 4 pm to 9 pm
afternoon_excess = np.sum(real_day_generation['Generación Real (MWh)'][16:21]) - np.sum(programmed_day_generation[16:21])
afternoon_excess

2027.279494343602